//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenDBPerformance.RavenDB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RavenDB.IRavenDbService")]
    public interface IRavenDbService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRavenDbService/Store", ReplyAction="http://tempuri.org/IRavenDbService/StoreResponse")]
        void Store(RavenDbWcfHost.WcfData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRavenDbService/Store", ReplyAction="http://tempuri.org/IRavenDbService/StoreResponse")]
        System.Threading.Tasks.Task StoreAsync(RavenDbWcfHost.WcfData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRavenDbServiceChannel : RavenDBPerformance.RavenDB.IRavenDbService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RavenDbServiceClient : System.ServiceModel.ClientBase<RavenDBPerformance.RavenDB.IRavenDbService>, RavenDBPerformance.RavenDB.IRavenDbService {
        
        public RavenDbServiceClient() {
        }
        
        public RavenDbServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RavenDbServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RavenDbServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RavenDbServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Store(RavenDbWcfHost.WcfData data) {
            base.Channel.Store(data);
        }
        
        public System.Threading.Tasks.Task StoreAsync(RavenDbWcfHost.WcfData data) {
            return base.Channel.StoreAsync(data);
        }
    }
}
